#!/usr/bin/env bash
# Fetches the live model list from each provider and writes it as comments into .env.
set -euo pipefail
cd "$(dirname "$0")/.."
set -a; . ./.env; set +a
B='# >>> available models (generated by scripts/list-models.sh)'; E='# <<< available models'
out=$(mktemp)
{
  echo "$B"
  echo "# LLM_PROVIDER=openai  (paid, uses credits)"
  curl -s https://api.openai.com/v1/models -H "Authorization: Bearer $OPENAI_API_KEY" \
    | jq -r '.data[].id | select(test("^(gpt|o[0-9])")) | select(test("audio|realtime|image|tts|transcribe|search|embedding|moderation|instruct")|not)' | sort | sed 's/^/#   /'
  echo "# LLM_PROVIDER=ollama  (local, free)"
  curl -s localhost:11434/api/tags | jq -r '.models[].name' | sed 's/^/#   /'
  echo "# LLM_PROVIDER=openrouter  (free, tool-capable; ids must end in :free)"
  curl -s https://openrouter.ai/api/v1/models | jq -r '.data[] | select((.id|endswith(":free")) or .id=="openrouter/free") | select(.supported_parameters|index("tools")) | .id' | sort | sed 's/^/#   /'
  echo "$E"
} > "$out"
grep -v -e "^$B" -e "^$E" -e '^#   ' -e '^# LLM_PROVIDER=.*(' .env > "$out.env" || true
cat "$out.env" "$out" > .env && rm "$out" "$out.env"
